version: '3'

services:
  computer-agent:
    build: .
    ports:
      - "127.0.0.1:5900:5900"  # VNC port - only bind to localhost
      - "127.0.0.1:5000:5000"  # MCP server port - only bind to localhost
    environment:
      - DISPLAY=:1
      - MCP_API_KEY=${MCP_API_KEY}
      - MCP_RATE_LIMIT=${MCP_RATE_LIMIT:-60}
      - MCP_BIND_HOST=0.0.0.0  # Inside container, bind to all interfaces
      - MCP_PORT=5000
      - MCP_DEBUG=${MCP_DEBUG:-False}
    volumes:
      - ./screenshots:/app/screenshots
      - ./reference_images:/app/reference_images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
