apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: computer-agent
spec:
  template:
    spec:
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/computer-agent:latest
        ports:
        - containerPort: 5900
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        env:
        - name: DISPLAY
          value: ":1"
